import * as React from "react";
import { Box, Container, Typography, Button, Divider } from "@mui/material";
import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import { useNavigate } from "react-router-dom";

function Section({ title, children }) {
  return (
    <Box sx={{ mb: 3 }}>
      <Typography variant="h6" fontWeight={700} gutterBottom>{title}</Typography>
      <Typography variant="body2" color="text.secondary" component="div" sx={{ lineHeight: 1.8 }}>
        {children}
      </Typography>
    </Box>
  );
}

/** Plain-language terms of service. Public page, linked from login and Help. */
export default function Terms() {
  const navigate = useNavigate();
  return (
    <Box sx={{ minHeight: "100vh", bgcolor: "background.default", py: 5 }}>
      <Container maxWidth="md">
        <Button startIcon={<ArrowBackRoundedIcon />} onClick={() => navigate(-1)} sx={{ mb: 2 }}>
          Back
        </Button>
        <Typography variant="h4" fontWeight={800} gutterBottom>Terms of Service</Typography>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Last updated: July 2026
        </Typography>
        <Divider sx={{ my: 3 }} />

        <Section title="What Bandly is">
          Bandly is an IELTS preparation platform: teachers create and import practice tests, students
          take them, and the platform grades and explains the results. It is a study tool — scores here
          are practice estimates, not official IELTS results.
        </Section>

        <Section title="Your account">
          Keep your password private and use your own account. Teachers are responsible for the content
          of the tests they upload; don't upload material you have no right to use.
        </Section>

        <Section title="Acceptable use">
          Don't attempt to break, overload or reverse-engineer the service, access other people's data,
          or use the platform for anything unlawful. Accounts that do may be disabled.
        </Section>

        <Section title="AI-generated content">
          Grading suggestions, explanations and feedback are partly generated by AI and reviewed by
          teachers where noted. They can occasionally be wrong — use the "Report" buttons when something
          looks off.
        </Section>

        <Section title="Availability">
          We aim to keep the service running smoothly but provide it "as is", without a guarantee of
          uninterrupted availability. We may update features over time.
        </Section>

        <Section title="Contact">
          Questions about these terms: <strong>congduy.workspace@gmail.com</strong>.
        </Section>
      </Container>
    </Box>
  );
}
